### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [tifkim/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tifkim** [comment]
Thanks for the tip! Added <meta name="viewport" content="width=device-width, initial-scale=1"> and it seemed to do the trick testing on my phone. Made a big difference.
